import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import {
  addTracksToSpotifyPlaylist,
  createSpotifyPlaylist,
  fetchDiscoveryTrackUris,
  fetchMySpotifyUserId,
  fetchNewReleaseTrackUris,
  fetchTopTrackUris,
  refreshAccessToken,
} from "@/lib/spotify";

function redirectWith(url: string, params: Record<string, string>) {
  const target = new URL(url, "http://localhost");
  for (const [key, value] of Object.entries(params)) {
    target.searchParams.set(key, value);
  }
  return NextResponse.redirect(`${target.pathname}?${target.searchParams.toString()}`);
}

export async function POST(request: Request) {
  const formData = await request.formData();
  const mixType = String(formData.get("mixType") ?? "top-tracks");
  const redirectTo = String(formData.get("redirectTo") ?? "/playlists");

  const cookieStore = await cookies();
  const refreshToken = cookieStore.get("spotify_refresh_token")?.value;
  if (!refreshToken) {
    return redirectWith(redirectTo, {
      created: "failed",
      reason: "Connect Spotify first.",
      auth: "required",
    });
  }

  try {
    const accessToken = await refreshAccessToken(refreshToken);
    const userId = await fetchMySpotifyUserId(accessToken);

    let uris: string[] = [];
    let playlistName = "";

    if (mixType === "top-tracks") {
      uris = await fetchTopTrackUris(accessToken, 20);
      playlistName = "Spotify Tracker - Top Tracks";
    } else if (mixType === "new-releases") {
      uris = await fetchNewReleaseTrackUris(20);
      playlistName = "Spotify Tracker - New Releases";
    } else {
      uris = await fetchDiscoveryTrackUris(accessToken, 20);
      playlistName = "Spotify Tracker - Discovery Mix";
    }

    if (!uris.length) {
      return redirectWith(redirectTo, {
        created: "failed",
        reason: "No tracks found for this mix type.",
      });
    }

    const playlist = await createSpotifyPlaylist({
      accessToken,
      userId,
      name: playlistName,
      description: "Generated by Spotify Tracker",
      isPublic: false,
    });

    await addTracksToSpotifyPlaylist({
      accessToken,
      playlistId: playlist.id,
      uris,
    });

    return redirectWith(redirectTo, {
      created: "ok",
      type: mixType,
      count: String(uris.length),
      playlistUrl: playlist.externalUrl,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Playlist creation failed";
    const needsReconnect =
      message.toLowerCase().includes("insufficient") ||
      message.toLowerCase().includes("permissions") ||
      message.toLowerCase().includes("scope");
    return redirectWith(redirectTo, {
      created: "failed",
      reason: message.slice(0, 180),
      auth: needsReconnect ? "reconnect" : "none",
    });
  }
}
