import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import {
  addTracksToSpotifyPlaylist,
  createSpotifyPlaylist,
  fetchMySpotifyUserId,
  refreshAccessToken,
} from "@/lib/spotify";
import { readHistoryEntries } from "@/lib/storage";
import { buildPlaylistInsights } from "@/lib/playlist-recommendations";

function redirectWith(url: string, params: Record<string, string>) {
  const target = new URL(url, "http://localhost");
  for (const [key, value] of Object.entries(params)) {
    target.searchParams.set(key, value);
  }
  return NextResponse.redirect(`${target.pathname}?${target.searchParams.toString()}`);
}

export async function POST(request: Request) {
  const formData = await request.formData();
  const mixType = String(formData.get("mixType") ?? "most-played-month");
  const redirectTo = String(formData.get("redirectTo") ?? "/playlists");

  const cookieStore = await cookies();
  const refreshToken = cookieStore.get("spotify_refresh_token")?.value;
  if (!refreshToken) {
    return redirectWith(redirectTo, {
      created: "failed",
      reason: "Connect Spotify first.",
      auth: "required",
    });
  }

  try {
    const accessToken = await refreshAccessToken(refreshToken);
    const userId = await fetchMySpotifyUserId(accessToken);
    const entries = await readHistoryEntries();
    const insights = buildPlaylistInsights(entries);

    const mix = insights.mixes.find((item) => item.id === mixType);
    const uris = (mix?.tracks ?? []).map((track) => track.uri).filter(Boolean).slice(0, 100);
    const playlistName = `Spotify Tracker - ${mix?.title ?? "Custom Mix"}`;

    if (!uris.length) {
      return redirectWith(redirectTo, {
        created: "failed",
        reason: "No Spotify-track URIs found for this mix.",
      });
    }

    const playlist = await createSpotifyPlaylist({
      accessToken,
      userId,
      name: playlistName,
      description: "Generated by Spotify Tracker",
      isPublic: false,
    });

    await addTracksToSpotifyPlaylist({
      accessToken,
      playlistId: playlist.id,
      uris,
    });

    return redirectWith(redirectTo, {
      created: "ok",
      type: mixType,
      count: String(uris.length),
      playlistUrl: playlist.externalUrl,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Playlist creation failed";
    const needsReconnect =
      message.toLowerCase().includes("insufficient") ||
      message.toLowerCase().includes("permissions") ||
      message.toLowerCase().includes("scope");
    return redirectWith(redirectTo, {
      created: "failed",
      reason: message.slice(0, 180),
      auth: needsReconnect ? "reconnect" : "none",
    });
  }
}
